# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 14:19
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20180116_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='\u673a\u6784\u63cf\u8ff0'),
        ),
    ]
